name: Releases
on:
  push:
    branches:
      - master
env:
  FLUTTER_VERSION: 3.10.5
  LINUX_DEPENDENCIES: git wget unzip python3 zip xz-utils curl clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev libjsoncpp-dev cmake-data libjsoncpp25 libsecret-1-dev libsecret-1-0 librhash0 libsqlite3-dev libappindicator3-dev gettext libwebkit2gtk-4.1-dev

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - uses: actions/setup-java@v2
        with:
            distribution: "zulu"
            java-version: "11"

      - name: Set up Checkout
        uses: actions/checkout@v3

      # Add caching for Flutter setup and dependencies
      # - name: Cache Flutter
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.pub-cache
      #     key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          channel: "stable"

      - name: Build release APK
        run: flutter build apk --release

      # Rest of the steps for generating changelog and creating release
      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          files: |
              build/app/outputs/flutter-apk/*.apk
              # build/ios/iphoneos/app.ipa
              # build/macos/Build/Products/Release/yoyo.mac.zip
              # yy-linux-x86_64.tar.gz
              # yy-windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
